name: Daily Scraper

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # 🔥 INI KUNCINYA

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas openpyxl

      - name: Run scraper
        run: python inspiredinnovatorlist.py

      - name: Commit & Push result
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "bot@github.com"
          git add inspired_data.xlsx
          git diff --cached --quiet || git commit -m "🤖 auto update data"
          git push
