name: Daily Scraper

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas openpyxl

      - name: Run script
        run: python inspiredinnovatorlist.py
